name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Rye
        run: |
          curl -sSf https://rye.astral.sh/get | bash
          echo "$HOME/.rye/shims" >> $GITHUB_PATH
        env:
          RYE_VERSION: "0.44.0"
          RYE_INSTALL_OPTION: "--yes"

      - name: Install dependencies
        run: rye sync --all-features

      - name: Lint
        run: ./scripts/lint

      - name: Build
        run: rye build

      - name: Test
        run: ./scripts/test
